In [15]:
#First Dataset
import pandas as pd
df=pd.read_csv("/content/Expt11.csv")
df

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [16]:
df.size

240

In [17]:
df.shape

(60, 4)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     60 non-null     object
 1   Gender      60 non-null     object
 2   Department  60 non-null     object
 3   Grade       60 non-null     object
dtypes: object(4)
memory usage: 2.0+ KB

In [19]:
df.head()

  Student  Gender Department Grade
0      S1    Male        CSE     A
1      S2  Female         IT     B
2      S3  Female        CSE     A
3      S4    Male        ECE     C
4      S5    Male         IT     B

In [20]:
df.tail()

   Student  Gender  Department Grade
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [21]:
df.sample(5)

   Student  Gender  Department Grade
31     S32  Female         ECE     B
6       S7    Male  Mechanical     B
28     S29    Male  Mechanical     C
24     S25    Male          IT     A
5       S6  Female         CSE     A

In [22]:
df.columns

Index(['Student', 'Gender', 'Department', 'Grade'], dtype='object')

In [23]:
df.isnull().sum()

Student       0
Gender        0
Department    0
Grade         0
dtype: int64

In [24]:

print(df.duplicated().sum())

0

In [25]:
print(df.nunique())

Student       60
Gender         2
Department     4
Grade          3
dtype: int64

In [26]:
#Count Stdents in each grade
#Find how many students obtained each grade.
print(df['Grade'].value_counts())

Grade
B    24
A    22
C    14
Name: count, dtype: int64

In [27]:
print(df['Gender'].value_counts())

Gender
Male      30
Female    30
Name: count, dtype: int64

In [28]:
#Number of students in each department
print("Department Count")
print(df['Department'].value_counts())

Department Count
Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [29]:
#Percentage Distribution of grades
print("Grade Percentage")
print(df['Grade'].value_counts(normalize=True)*100)

Grade Percentage
Grade
B    40.000000
A    36.666667
C    23.333333
Name: proportion, dtype: float64

In [30]:
#Gender vs Grade Analyis
print(pd.crosstab(df['Gender'],df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

In [31]:
#Department vs Gender
print(pd.crosstab(df['Department'],df['Gender']))

Gender      Female  Male
Department
CSE             12     8
ECE              5     6
IT               9     9
Mechanical       4     7

In [32]:
print(pd.crosstab(df['Department'],df['Grade']))

Grade        A  B  C
Department
CSE         13  4  3
ECE          2  5  4
IT           7  8  3
Mechanical   0  7  4

In [33]:
#Deprtment vs Grade Percentage
print(pd.crosstab(df['Department'],df['Grade'],normalize='index')*100)

Grade               A          B          C
Department
CSE         65.000000  20.000000  15.000000
ECE         18.181818  45.454545  36.363636
IT          38.888889  44.444444  16.666667
Mechanical   0.000000  63.636364  36.363636

In [34]:
#Grouping Data
print(df.groupby('Department')['Grade'].value_counts())

Department  Grade
CSE         A        13
            B         4
            C         3
ECE         B         5
            C         4
            A         2
IT          B         8
            A         7
            C         3
Mechanical  B         7
            C         4
Name: count, dtype: int64

In [35]:
#B. Second Dataset
import pandas as pd
data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8','O9','O10'],

'Category':['Electronics','Clothing','Electronics','Grocery','Clothing',
            'Electronics','Grocery','Clothing','Electronics','Grocery'],

'Payment_Method':['UPI','Card','UPI','Cash','Card',
                  'UPI','Cash','Card','UPI','Cash'],

'Delivery_Type':['Express','Standard','Express','Standard','Express',
                 'Standard','Express','Standard','Express','Standard'],

'Customer_Type':['New','Returning','Returning','New','Returning',
                 'New','Returning','New','Returning','New']
}
df=pd.DataFrame(data)
print(df)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       O1  Electronics            UPI       Express           New
1       O2     Clothing           Card      Standard     Returning
2       O3  Electronics            UPI       Express     Returning
3       O4      Grocery           Cash      Standard           New
4       O5     Clothing           Card       Express     Returning
5       O6  Electronics            UPI      Standard           New
6       O7      Grocery           Cash       Express     Returning
7       O8     Clothing           Card      Standard           New
8       O9  Electronics            UPI       Express     Returning
9      O10      Grocery           Cash      Standard           New

In [36]:
#Frequency Count
#Count how many orders in each category.
print(df['Category'].value_counts())

Category
Electronics    4
Clothing       3
Grocery        3
Name: count, dtype: int64

In [37]:
#Pecentage Distribution
print(df['Category'].value_counts(normalize=True)*100)

Category
Electronics    40.0
Clothing       30.0
Grocery        30.0
Name: proportion, dtype: float64

In [38]:
#Frequency of payment methods
print(df['Payment_Method'].value_counts())

Payment_Method
UPI     4
Card    3
Cash    3
Name: count, dtype: int64

In [39]:
#Unique Values
#Display all unique categories.
print(df['Category'].unique())

['Electronics' 'Clothing' 'Grocery']

In [40]:
#Number of Unique Values
print(df['Category'].nunique())

3

In [41]:
#Cross Tabulation
#Category vs Payment Method
print(pd.crosstab(df['Category'],df['Payment_Method']))

Payment_Method  Card  Cash  UPI
Category
Clothing           3     0    0
Electronics        0     0    4
Grocery            0     3    0

In [42]:
#Filtering Data
#Example:Orders from electronics category
electronics_orders=df[df['Category']=='Electronics']
print(electronics_orders)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       O1  Electronics            UPI       Express           New
2       O3  Electronics            UPI       Express     Returning
5       O6  Electronics            UPI      Standard           New
8       O9  Electronics            UPI       Express     Returning

In [43]:
#Sorting Data
sorted_df=df.sort_values(by='Category')
print(sorted_df)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
1       O2     Clothing           Card      Standard     Returning
4       O5     Clothing           Card       Express     Returning
7       O8     Clothing           Card      Standard           New
0       O1  Electronics            UPI       Express           New
2       O3  Electronics            UPI       Express     Returning
5       O6  Electronics            UPI      Standard           New
8       O9  Electronics            UPI       Express     Returning
3       O4      Grocery           Cash      Standard           New
6       O7      Grocery           Cash       Express     Returning
9      O10      Grocery           Cash      Standard           New

In [44]:
#Grouping
#Orders by category and payment method
print(df.groupby('Category')['Payment_Method'].value_counts())

Category     Payment_Method
Clothing     Card              3
Electronics  UPI               4
Grocery      Cash              3
Name: count, dtype: int64